title: save-docs
description: Documentation for save files; bugs, my save editors and API, along with any tools I use/developed.
theme: just-the-docs

url: https://n123git.github.io/save-docs

aux_links: # remove if you don't want this link to appear on your pages yes I copy/pasted the template :>>>>>>>>>>>>>>
 Github: https://github.com/n123git/save-docs

color_scheme: light
toggle_color_scheme: dark
toggle_auto_mode: true
toggle_text_1: "-> Dark Mode"
toggle_text_2: "-> Light Mode"
