title: save-docs
description: Documentation for save files; bugs, my save editors and API, along with any tools I use/developed.
theme: just-the-docs

url: https://n123git.github.io/save-docs

aux_links: # remove if you don't want this link to appear on your pages yes I copy/pasted the template :>>>>>>>>>>>>>>
 Github: https://github.com/n123git/save-docs

# Initial theme (can be light, dark, or nil to default to system/browser)
color_scheme: light

# Which scheme the toggle switches to
toggle_color_scheme: dark

# Show toggle button on all pages (default)
toggle_page_url: nil

# Automatic switching based on OS preference
# toggle_auto_mode: true

toggle_icon: material/weather-night

